# Generated by Django 3.0.5 on 2020-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('profile', '0002_auto_20200609_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ManyToManyField(related_name='post_by', to='status.Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
