# Generated by Django 3.0.5 on 2020-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
        ('profile', '0004_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='status.Status'),
        ),
    ]
