# Generated by Django 3.0.5 on 2020-06-26 08:23

from django.db import migrations, models
import vgo.apps.post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vgo.apps.post.models.upload_location),
        ),
    ]
