# Generated by Django 3.0.5 on 2020-06-26 10:52

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200626_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
