# Generated by Django 3.0.5 on 2020-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
