# Generated by Django 3.0.5 on 2020-06-26 11:20

from django.db import migrations, models
import django.db.models.deletion
import vgo.apps.post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200626_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vgo.apps.post.models.upload_location, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
