# Generated by Django 3.0.5 on 2020-06-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200619_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='profile',
            new_name='author',
        ),
    ]
